jobs/urls.py
from django.conf.urls import url, include
from jobs import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/(?P<id>\d+)/$', views.details, name='details'),
    url(r'^postnewjob/$', views.post_new_job, name='postnewjob'),
    url(r'^postnewjob/thanks/(?P<id>\d+)/$', views.thanks, name='thanks')
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^', include('jobs.urls')),
]

jobs/models.py
from django.db import models
from datetime import datetime


class Company(models.Model):
    name = models.CharField(max_length=200)
    industry = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Companies'


class Job(models.Model):
    title = models.CharField(max_length=200)
    job_description = models.TextField()
    date_posted = models.DateTimeField(default=datetime.now)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + " - " + self.company.name


class User(models.Model):
    name = models.CharField(max_length=200)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

jobs/forms.py
from django import forms
from jobs import models


class PostNewJobForm(forms.ModelForm):
    class Meta:
        model = models.Job
        fields = [
            'title',
            'job_description',
            'company'
        ]

    def __init__(self, *args, **kwargs):
        super(PostNewJobForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget = forms.TextInput(attrs={
            'placeholder': 'Eg. Cashier'
        })
        self.fields['job_description'].widget = forms.Textarea(attrs={
            'placeholder': 'A brief description of the duties of the job',
            'class': 'materialize-textarea'
        })

jobs/views.py
from django.shortcuts import render, reverse
from jobs.models import Job
from jobs import forms
from django.http import HttpResponseRedirect


def index(request):
    jobs = Job.objects.all()[:10]
    context = {
        'title': 'Job Listings',
        'jobs': jobs
    }
    return render(request, 'jobs/index.html', context)


def details(request, id):
    job = Job.objects.get(id=id)
    context = {
        'job': job
    }
    return render(request, 'jobs/details.html', context)


def post_new_job(request):
    if request.method == 'POST':
        form = forms.PostNewJobForm(request.POST)
        if form.is_valid():
            instance = form.save()
            return HttpResponseRedirect('thanks/' + str(instance.pk) + '/')
    else:
        form = forms.PostNewJobForm()
    context = {
        'form': form
    }
    return render(request, 'jobs/postnewjob.html', context)


def thanks(request, id):
    job = Job.objects.get(id=id)
    context = {
        'job': job
    }
    return render(request, 'jobs/thanks.html', context)

jobs/templates/jobs/details.html
{% extends 'jobs/layout.html' %}

{% block content %}
    <div class="container">
    <h3 class="center-align green">Job Details</h3>
        <div class="card blue-grey lighten-3">
            <div class="card-content">
                <span class="card-title">{{ job }} - {{ job.company.industry }}</span>
                <p>{{ job.job_description }}</p>
            </div>
            <div class="card-action">Posted: {{ job.date_posted }}</div>
        </div>
        <div class="row">
            <a href="/jobs/" class="btn col s2">Back</a>
        </div>
    </div>
{% endblock %}

jobs/templates/jobs/index.html
{% extends 'jobs/layout.html' %}

{% block content %}
    <div class="container">
        <h3 class="center-align green">{{ title }}</h3>
        <ul class="collection">
            {% for job in jobs %}
                <a href="/jobs/details/{{ job.id }}" class="collection-item"><li>{{ job }}</li></a>
            {% endfor %}
        </ul>
        <div class="row">
            <a href="postnewjob/" class="btn col s4 offset-s4">Post New Job</a>
        </div>
    </div>
{% endblock %}

jobs/templates/jobs/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <title>Django Djobs</title>
</head>
<body>
<header class="container center-align">
    <h1>Django Djobs</h1>
</header>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

jobs/templates/jobs/postnewjob.html
{% extends 'jobs/layout.html' %}

{% block content %}
    <div class="container">
    <h3 class="center-align green">Posting New Job</h3>
        <div class="row">
            <form class="s12" action="" method="post">
                {% csrf_token %}
                <div class="input-field col s12">
                    {{ form.company }}
                    <label for="id_company">Company</label>
                </div>
                <div class="input-field col s12">
                    {{ form.title }}
                    <label for="id_title" class="active">Job Title</label>
                </div>
                <div class="input-field col s12">
                    {{ form.job_description }}
                    <label for="id_job_description" class="active">Job Description</label>
                </div>
                <div class="row">
                    <a href="/jobs/" class="btn col s2">Back</a>
                    <button class="btn waves-effect waves-light col s3 offset-s7" type="submit" name="action">Submit
                        <i class="material-icons right">send</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <!--Import jQuery before materialize.js-->
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<!-- Compiled and minified materialize JavaScript -->
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
	<script>
		$(document).ready(function() {
			$('select').material_select();
		});
	</script>
{% endblock %}

jobs/templates/jobs/thanks.html
{% extends 'jobs/layout.html' %}

{% block content %}
    <div class="container">
    <h3 class="center-align green">Posting New Job</h3>
        <div class="card green lighten-3">
            <div class="card-content">
                <span class="card-title center-align">Thank You!</span>
                <p>Your "{{ job.title }}" job for {{ job.company }} was posted successfully</p>
            </div>
            <div class="card-action">Posted: {{ job.date_posted }}</div>
        </div>
        <div class="row">
            <a href="/jobs/" class="btn col s2">Back</a>
            <a href="/jobs/details/{{ job.id }}/" class="btn col s3 offset-s7">View Job</a>
        </div>
    </div>
{% endblock %}